from pathlib import Path
p=Path('/mnt/data/evan_work2/vip.html'); s=p.read_text()
# Add level card after dashboard
needle='<section class="card"><h2>📊 Tableau de bord</h2>'
idx=s.find(needle)
# easier insert before notifications section
needle2='<section class="card"><h2>🔔 Notifications</h2>'
insert='''<section class="card"><h2>🏆 Niveau & XP</h2><div class="grid3"><div class="stat"><span>⭐ XP</span><b id="xpValue">0</b></div><div class="stat"><span>🏆 Niveau</span><b id="levelValue">1</b></div><div class="stat"><span>🎯 Prochain niveau</span><b id="nextXpValue">100</b></div></div><p id="levelProgress" class="muted small"></p></section>\n'''
s=s.replace(needle2,insert+needle2,1)
# Replace notifications content to include live status
s=s.replace('<section class="card"><h2>🔔 Notifications</h2><div id="notifications"></div></section>', '<section class="card"><h2>🔔 Notifications <span id="notifCount" class="badge vip">0</span></h2><div id="notifications"></div><button class="ghost" onclick="markNotificationsRead()">✓ Tout marquer comme lu</button></section>')
# Replace visitor admin with full admin section after it
needle='<section class="card" id="adminVisitors" style="display:none">'
start=s.find(needle); end=s.find('</section>', start)+len('</section>')
admin='''<section class="card" id="adminPanel" style="display:none"><h2>👑 Panneau Admin privé</h2><p class="muted">Réservé à ton compte administrateur. Ici tu contrôles les utilisateurs, signalements, sessions et annonces publiques.</p><div class="grid3"><div class="stat"><span>👀 Visiteurs total</span><b id="adminTotalVisitors">0</b></div><div class="stat"><span>📅 Aujourd’hui</span><b id="adminTodayVisitors">0</b></div><div class="stat"><span>👥 Comptes</span><b id="adminUsersCount">0</b></div></div><h3>👥 Utilisateurs</h3><div id="adminUsers" class="small"></div><h3>🚨 Signalements</h3><div id="adminReports" class="small"></div><h3>📢 Nouvelle annonce publique</h3><input id="annTitle" placeholder="Titre de l’annonce" maxlength="120"><textarea id="annMessage" placeholder="Message visible par tout le monde, même sans compte" maxlength="500" style="width:100%;min-height:100px;padding:12px;border-radius:12px;background:#090b18;color:white;border:1px solid #30334d"></textarea><label><input id="annVipOnly" type="checkbox"> Réserver aux VIP</label><button onclick="createAnnouncement()">📢 Publier l’annonce</button><div id="adminAnnouncementResult" class="muted small"></div><h3>📢 Annonces actuelles</h3><div id="adminAnnouncements" class="small"></div><h3>📱 Sessions actives</h3><div id="adminSessions" class="small"></div><button class="ghost" onclick="loadAdmin()">🔄 Actualiser le panneau</button></section>'''
s=s[:start]+s[start:end]+admin+s[end:]
# Add user session management in security section before newPassword
s=s.replace('<button class="ghost" onclick="clearSecurityLog()">🧹 Effacer le journal de sécurité</button><input id="newPassword"', '<button class="ghost" onclick="clearSecurityLog()">🧹 Effacer le journal de sécurité</button><div id="mySessions" class="small" style="margin-top:10px"></div><input id="newPassword"')
# Modify refresh to load admin and notifications; currently calls visitors unconditionally but it hides if not admin.
s=s.replace('await loadDashboard();await loadVisitors();', 'await loadDashboard();await loadNotifications();await loadSecurity();await loadVisitors();await loadAdmin();')
# Modify dashboard notifications rendering to not use announcements as notifications: leave messages but okay. Add function before loadDashboard
needle='async function loadDashboard()'
func='''async function loadNotifications(){try{let d=await api('/api/notifications');$('notifCount').textContent=d.unread||0;$('notifications').innerHTML=d.notifications.length?d.notifications.map(x=>`<div class="item" style="opacity:${x.read_at?.length?0.7:1}"><b>${esc(x.title)}</b><br><span class="muted">${esc(x.message)}</span><br><small class="muted">${esc(x.created_at)}</small>${!x.read_at?` <button class="ghost small" onclick="markOneRead(${x.id})">Lu</button>`:''}</div>`).join(''):'<p class="muted">Aucune notification pour le moment.</p>';}catch(e){}}\nasync function markOneRead(id){try{await api('/api/notifications/read',{method:'POST',body:JSON.stringify({id})});await loadNotifications()}catch{}}\nasync function markNotificationsRead(){try{await api('/api/notifications/read',{method:'POST',body:JSON.stringify({})});await loadNotifications()}catch{}}\n\n'''+needle
s=s.replace(needle,func,1)
# rewards function display XP/level
s=s.replace("$('rewards').innerHTML=d.badges.map", "$('xpValue').textContent=d.xp;$('levelValue').textContent=d.level;$('nextXpValue').textContent=d.nextLevelXp;$('levelProgress').textContent=`${d.xp} XP · ${Math.max(0,d.nextLevelXp-d.xp)} XP avant le niveau suivant`;$('rewards').innerHTML=d.badges.map")
# security load sessions
s=s.replace("let html=d.sessions.map(x=>`🟢 ${esc(x.device)} — session active`).join('<br>');", "$('mySessions').innerHTML='<b>📱 Mes appareils</b><br>'+d.sessions.map(x=>`<div class=\"item\">${x.current?'🟢':'⚪'} ${esc(x.user_agent||'Appareil')}<br><span class=\"muted\">IP ${esc(x.ip||'')} · dernière activité ${esc(x.last_seen||'')}</span>${!x.current?`<button class=\"ghost small\" onclick=\"logoutSession('${x.id}')\">Déconnecter</button>`:''}</div>`).join('');let html=d.sessions.map(x=>`${x.current?'🟢':'⚪'} ${esc(x.user_agent||'Appareil')} — ${esc(x.ip||'')}`).join('<br>');")
# Add admin functions before loadVisitors
needle='async function loadVisitors()'
func='''async function logoutSession(id){try{await api('/api/sessions/'+encodeURIComponent(id),{method:'DELETE'});await loadSecurity()}catch(e){alert(e.message)}}\nasync function loadAdmin(){try{let d=await api('/api/admin/overview');$('adminPanel').style.display='block';$('adminTotalVisitors').textContent=d.stats.totalVisitors;$('adminTodayVisitors').textContent=d.stats.todayVisitors;$('adminUsersCount').textContent=d.users.length;$('adminUsers').innerHTML=d.users.length?d.users.map(u=>`<div class="item"><b>${esc(u.display_name)}</b> <span class="badge ${['active','trialing'].includes(u.subscription_status)?'vip':'free'}">${['active','trialing'].includes(u.subscription_status)?'⭐ VIP':'🔔 FREE'}</span><br><span class="muted">${esc(u.email)} · créé ${esc(u.created_at)}</span>${u.id!==d.users.find(x=>x.email===document.getElementById('loginEmail')?.value)?.id?`<button class="danger small" onclick="deleteAdminUser(${u.id})">Supprimer</button>`:''}</div>`).join(''):'Aucun utilisateur';$('adminReports').innerHTML=d.reports.length?d.reports.map(r=>`<div class="item"><b>🚨 ${esc(r.content_title)}</b><br>${esc(r.body)}<br><span class="muted">Signalé par ${esc(r.display_name)} · ${esc(r.reason)} · ${esc(r.created_at)}</span></div>`).join(''):'Aucun signalement.';let a=await api('/api/announcements');$('adminAnnouncements').innerHTML=a.announcements.length?a.announcements.map(x=>`<div class="item"><b>${esc(x.title)}</b><br>${esc(x.message)}<br><small class="muted">${esc(x.created_at)}</small></div>`).join(''):'Aucune annonce.';let ss=await api('/api/admin/sessions');$('adminSessions').innerHTML=ss.sessions.length?ss.sessions.map(x=>`<div class="item">🟢 ${esc(x.display_name)} · ${esc(x.ip)}<br><span class="muted">${esc(x.user_agent)} · ${esc(x.last_seen)}</span></div>`).join(''):'Aucune session.';}catch(e){$('adminPanel').style.display='none';}}\nasync function deleteAdminUser(id){if(!confirm('Supprimer ce compte ?'))return;try{await api('/api/admin/users/'+id,{method:'DELETE'});await loadAdmin()}catch(e){alert(e.message)}}\nasync function createAnnouncement(){let title=$('annTitle').value.trim(),message=$('annMessage').value.trim();if(!title||!message)return alert('Titre et message requis.');try{await api('/api/admin/announcements',{method:'POST',body:JSON.stringify({title,message,vipOnly:$('annVipOnly').checked})});$('annTitle').value='';$('annMessage').value='';$('adminAnnouncementResult').textContent='Annonce publiée : elle est visible publiquement.';await loadAdmin();}catch(e){alert(e.message)}}\n\n'''+needle
s=s.replace(needle,func,1)
# polling notifications and admin
s=s.replace('refresh();\n</script>', 'refresh();\nsetInterval(()=>{loadNotifications();},10000);\n</script>')
p.write_text(s)

# index: add public announcement box to gate
p=Path('/mnt/data/evan_work2/index.html'); s=p.read_text()
needle='<p class="gate-note">🔐 Les fonctions et données personnelles restent protégées par ton compte.</p>'
insert='<div id="publicAnnouncements" style="margin-top:18px;text-align:left"></div>\n      '+needle
s=s.replace(needle,insert,1)
# add public loader before refreshAccountButton call
needle='    refreshAccountButton();'
func='''    async function loadPublicAnnouncements(){try{const r=await fetch(API_BASE+'/api/announcements');const d=await r.json();const box=document.getElementById('publicAnnouncements');if(!box)return;box.innerHTML=d.announcements?.length?`<div class="panel" style="padding:16px"><div class="kicker">📢 ANNONCES PUBLIQUES</div>${d.announcements.slice(0,5).map(x=>`<div style="padding:10px 0;border-bottom:1px solid var(--line)"><b>${escapeHtml(x.title)}</b><div style="color:var(--muted)">${escapeHtml(x.message)}</div><small style="color:var(--muted)">${escapeHtml(x.created_at)}</small></div>`).join('')}</div>`:'';}catch{}}\n    loadPublicAnnouncements();\n    setInterval(loadPublicAnnouncements,10000);\n    refreshAccountButton();'''
s=s.replace(needle,func,1)
p.write_text(s)
