from pathlib import Path
p=Path('/mnt/data/evan_work2/server.js')
s=p.read_text()
s=s.replace('import dotenv from "dotenv";','import dotenv from "dotenv";\nimport crypto from "crypto";')
s=s.replace('CREATE TABLE IF NOT EXISTS visitor_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, ip TEXT NOT NULL, path TEXT NOT NULL, method TEXT NOT NULL, user_id INTEGER, user_agent TEXT DEFAULT \'\', referer TEXT DEFAULT \'\', created_at TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL);', '''CREATE TABLE IF NOT EXISTS visitor_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, ip TEXT NOT NULL, path TEXT NOT NULL, method TEXT NOT NULL, user_id INTEGER, user_agent TEXT DEFAULT '', referer TEXT DEFAULT '', created_at TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS notifications (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, type TEXT NOT NULL, title TEXT NOT NULL, message TEXT NOT NULL, read_at TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS user_sessions (id TEXT PRIMARY KEY, user_id INTEGER NOT NULL, user_agent TEXT DEFAULT '', ip TEXT DEFAULT '', created_at TEXT DEFAULT CURRENT_TIMESTAMP, last_seen TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);''')
s=s.replace('app.get("/health", (req, res) => res.json({ ok: true, service: "evan-delcourt" }));', 'app.get("/health", (req, res) => res.json({ ok: true, service: "evan-delcourt" }));\nfunction createSession(req, userId){ const id=crypto.randomUUID(); db.prepare("INSERT INTO user_sessions(id,user_id,user_agent,ip) VALUES(?,?,?,?)").run(id,userId,String(req.headers["user-agent"]||"").slice(0,500),clientIp(req)); req.session.sessionId=id; req.session.sessionVersion=1; return id; }\nfunction touchSession(req){ if(req.session?.sessionId){ try{ db.prepare("UPDATE user_sessions SET last_seen=CURRENT_TIMESTAMP,ip=?,user_agent=? WHERE id=? AND user_id=?").run(clientIp(req),String(req.headers["user-agent"]||"").slice(0,500),req.session.sessionId,req.session.userId); }catch{} } }')
s=s.replace('  if (req.session.sessionVersion && Number(req.session.sessionVersion) !== Number(user.session_version)) return null;\n  return user;', '  if (req.session.sessionVersion && Number(req.session.sessionVersion) !== Number(user.session_version)) return null;\n  if (!req.session.sessionId) return null;\n  const sess=db.prepare("SELECT id FROM user_sessions WHERE id=? AND user_id=?").get(req.session.sessionId,user.id);\n  if (!sess) return null;\n  touchSession(req);\n  return user;')
s=s.replace('const open = new Set([\'/api/me\',\'/api/register\',\'/api/login\',\'/api/logout\',\'/api/free-subscribe\',\'/api/stripe/webhook\']);', 'const open = new Set([\'/api/me\',\'/api/register\',\'/api/login\',\'/api/logout\',\'/api/free-subscribe\',\'/api/stripe/webhook\',\'/api/announcements\']);')
s=s.replace('req.session.userId = result.lastInsertRowid; req.session.sessionVersion = 1;', 'req.session.userId = result.lastInsertRowid; createSession(req, result.lastInsertRowid);', 1)
# login block
s=s.replace('  req.session.userId = user.id; req.session.sessionVersion = user.session_version || 1;', '  req.session.userId = user.id; createSession(req, user.id);')
s=s.replace('app.post("/api/logout", (req,res) => {\n  req.session = null;\n  res.json({ok:true});\n});', 'app.post("/api/logout", (req,res) => {\n  if(req.session?.sessionId) { try { db.prepare("DELETE FROM user_sessions WHERE id=?").run(req.session.sessionId); } catch {} }\n  req.session = null;\n  res.json({ok:true});\n});')
# password change keep current session valid and update version; delete other sessions
s=s.replace('  db.prepare("UPDATE users SET password_hash=?, session_version=session_version+1 WHERE id=?").run(hash,user.id);\n  logSecurity(user.id,\'password_changed\',\'Mot de passe modifié\');\n  const fresh=db.prepare(\'SELECT session_version FROM users WHERE id=?\').get(user.id); req.session.sessionVersion=fresh.session_version;', '  db.prepare("UPDATE users SET password_hash=?, session_version=session_version+1 WHERE id=?").run(hash,user.id);\n  db.prepare("DELETE FROM user_sessions WHERE user_id=? AND id<>?").run(user.id,req.session.sessionId);\n  logSecurity(user.id,\'password_changed\',\'Mot de passe modifié\');\n  const fresh=db.prepare(\'SELECT session_version FROM users WHERE id=?\').get(user.id); req.session.sessionVersion=fresh.session_version;')
# activity XP notification hooks
s=s.replace('  db.prepare("INSERT INTO activity(user_id,title,action) VALUES(?,?,?)").run(user.id,title,action);', '  db.prepare("INSERT INTO activity(user_id,title,action) VALUES(?,?,?)").run(user.id,title,action);\n  notify(user.id,\'activity\',\'Activité enregistrée\',`+10 XP · ${action} : ${title}`);')
# comment insert
s=s.replace('  const r=db.prepare("INSERT INTO comments(user_id,content_type,content_title,body) VALUES(?,?,?,?)").run(user.id,type,title,body); res.json({ok:true,id:r.lastInsertRowid});', '  const r=db.prepare("INSERT INTO comments(user_id,content_type,content_title,body) VALUES(?,?,?,?)").run(user.id,type,title,body);\n  const admin=db.prepare("SELECT id FROM users WHERE lower(email)=lower(?) LIMIT 1").get(process.env.ADMIN_EMAIL||"none");\n  if(admin && admin.id!==user.id) notify(admin.id,\'comment\',\'Nouveau commentaire\',`${user.display_name} a commenté ${title}`);\n  res.json({ok:true,id:r.lastInsertRowid});')
# reply insert
s=s.replace('  const r=db.prepare("INSERT INTO comment_replies(comment_id,user_id,body) VALUES(?,?,?)").run(id,user.id,body); res.json({ok:true,id:r.lastInsertRowid});', '  const r=db.prepare("INSERT INTO comment_replies(comment_id,user_id,body) VALUES(?,?,?)").run(id,user.id,body);\n  const owner=db.prepare("SELECT user_id,content_title FROM comments WHERE id=?").get(id);\n  if(owner && owner.user_id!==user.id) notify(owner.user_id,\'reply\',\'Nouvelle réponse\',`${user.display_name} a répondu à ton commentaire sur ${owner.content_title}`);\n  res.json({ok:true,id:r.lastInsertRowid});')
# Add notify function before announcements route
marker='app.get("/api/announcements", (req,res) => {'
insert='''function notify(userId,type,title,message){ try{ db.prepare('INSERT INTO notifications(user_id,type,title,message) VALUES(?,?,?,?)').run(userId,type,String(title).slice(0,120),String(message).slice(0,300)); }catch{} }\n\napp.get('/api/notifications', (req,res)=>{ const u=currentUser(req); if(!u) return res.status(401).json({error:'Connexion requise.'}); const rows=db.prepare('SELECT id,type,title,message,read_at,created_at FROM notifications WHERE user_id=? ORDER BY id DESC LIMIT 50').all(u.id); res.json({notifications:rows,unread:rows.filter(x=>!x.read_at).length}); });\napp.post('/api/notifications/read', (req,res)=>{ const u=currentUser(req); if(!u) return res.status(401).json({error:'Connexion requise.'}); const id=Number(req.body.id||0); if(id) db.prepare('UPDATE notifications SET read_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?').run(id,u.id); else db.prepare('UPDATE notifications SET read_at=CURRENT_TIMESTAMP WHERE user_id=?').run(u.id); res.json({ok:true}); });\n\n'''+marker
s=s.replace(marker,insert)
# admin APIs before announcements
marker='app.get("/api/announcements", (req,res) => {'
admin='''app.get('/api/admin/overview',(req,res)=>{ const u=currentUser(req); if(!isAdmin(u)) return res.status(403).json({error:'Accès administrateur uniquement.'}); const users=db.prepare("SELECT id,display_name,email,subscription_status,created_at FROM users ORDER BY id DESC LIMIT 200").all(); const reports=db.prepare("SELECT r.id,r.reason,r.created_at,c.body,c.content_title,u.display_name FROM comment_reports r JOIN comments c ON c.id=r.comment_id JOIN users u ON u.id=r.user_id ORDER BY r.id DESC LIMIT 100").all(); const total=db.prepare('SELECT COUNT(*) c FROM visitor_logs').get().c; const today=db.prepare("SELECT COUNT(*) c FROM visitor_logs WHERE date(created_at)=date('now')").get().c; const vip=db.prepare("SELECT COUNT(*) c FROM users WHERE subscription_status IN ('active','trialing')").get().c; const free=db.prepare("SELECT COUNT(*) c FROM users WHERE subscription_status='inactive'").get().c; res.json({stats:{totalVisitors:total,todayVisitors:today,vip,free},users,reports}); });\napp.delete('/api/admin/users/:id',(req,res)=>{ const u=currentUser(req); if(!isAdmin(u)) return res.status(403).json({error:'Accès administrateur uniquement.'}); const id=Number(req.params.id); if(!id || id===u.id) return res.status(400).json({error:'Impossible de supprimer ce compte.'}); db.prepare('DELETE FROM users WHERE id=?').run(id); res.json({ok:true}); });\napp.post('/api/admin/announcements',(req,res)=>{ const u=currentUser(req); if(!isAdmin(u)) return res.status(403).json({error:'Accès administrateur uniquement.'}); const title=String(req.body.title||'').trim().slice(0,120), message=String(req.body.message||'').trim().slice(0,500); const vipOnly=req.body.vipOnly===true?1:0; if(!title||!message) return res.status(400).json({error:'Titre et message requis.'}); const r=db.prepare('INSERT INTO announcements(title,message,vip_only) VALUES(?,?,?)').run(title,message,vipOnly); const all=db.prepare('SELECT id FROM users').all(); for(const x of all) notify(x.id,'announcement','Nouvelle annonce',title); res.json({ok:true,id:r.lastInsertRowid}); });\napp.delete('/api/admin/announcements/:id',(req,res)=>{ const u=currentUser(req); if(!isAdmin(u)) return res.status(403).json({error:'Accès administrateur uniquement.'}); db.prepare('DELETE FROM announcements WHERE id=?').run(Number(req.params.id)); res.json({ok:true}); });\napp.get('/api/admin/sessions',(req,res)=>{ const u=currentUser(req); if(!isAdmin(u)) return res.status(403).json({error:'Accès administrateur uniquement.'}); const rows=db.prepare("SELECT s.id,s.user_id,s.ip,s.user_agent,s.created_at,s.last_seen,u.display_name,u.email FROM user_sessions s JOIN users u ON u.id=s.user_id ORDER BY s.last_seen DESC LIMIT 200").all(); res.json({sessions:rows}); });\n\n'''+marker
s=s.replace(marker,admin)
# security sessions route replace
old='''  const st=securitySettings(u.id);\n  const events=db.prepare('SELECT type,detail,created_at FROM security_events WHERE user_id=? ORDER BY id DESC LIMIT 20').all(u.id);\n  res.json({enabled:!!st.security_enabled,linkProtection:!!st.link_protection,spamProtection:!!st.spam_protection,sessions:[{device:'Session actuelle',created_at:new Date().toISOString()}],events});'''
new='''  const st=securitySettings(u.id);\n  const events=db.prepare('SELECT type,detail,created_at FROM security_events WHERE user_id=? ORDER BY id DESC LIMIT 20').all(u.id);\n  const sessions=db.prepare('SELECT id,ip,user_agent,created_at,last_seen FROM user_sessions WHERE user_id=? ORDER BY last_seen DESC').all(u.id).map(x=>({...x,current:x.id===req.session.sessionId}));\n  res.json({enabled:!!st.security_enabled,linkProtection:!!st.link_protection,spamProtection:!!st.spam_protection,sessions,events});'''
s=s.replace(old,new)
# logout all delete sessions
s=s.replace('  db.prepare(\'UPDATE users SET session_version=session_version+1 WHERE id=?\').run(u.id);\n  logSecurity(u.id,\'logout_all\',\'Toutes les sessions ont été invalidées\');', '  db.prepare(\'UPDATE users SET session_version=session_version+1 WHERE id=?\').run(u.id);\n  db.prepare(\'DELETE FROM user_sessions WHERE user_id=?\').run(u.id);\n  logSecurity(u.id,\'logout_all\',\'Toutes les sessions ont été invalidées\');')
# per-device logout
needle="app.post('/api/logout-all', (req,res) => {"
extra="""app.delete('/api/sessions/:id',(req,res)=>{ const u=currentUser(req); if(!u) return res.status(401).json({error:'Connexion requise.'}); const id=String(req.params.id); if(id===req.session.sessionId) return res.status(400).json({error:'Utilise Déconnexion pour la session actuelle.'}); db.prepare('DELETE FROM user_sessions WHERE id=? AND user_id=?').run(id,u.id); res.json({ok:true}); });\n\n"""
s=s.replace(needle,extra+needle)
# rewards replace entire endpoint body by locating
start=s.index('app.get("/api/rewards"')
end=s.index('app.get("/api/announcements"', start)
rewards='''app.get("/api/rewards", (req,res) => {\n  const user=currentUser(req); if(!user) return res.status(401).json({error:"Connecte-toi d'abord."});\n  const activity=db.prepare("SELECT COUNT(*) c FROM activity WHERE user_id=?").get(user.id).c;\n  const likes=db.prepare("SELECT COUNT(*) c FROM likes WHERE user_id=?").get(user.id).c;\n  const comments=db.prepare("SELECT COUNT(*) c FROM comments WHERE user_id=?").get(user.id).c;\n  const replies=db.prepare("SELECT COUNT(*) c FROM comment_replies WHERE user_id=?").get(user.id).c;\n  const days=Math.max(0,Math.floor((Date.now()-new Date(user.created_at).getTime())/86400000));\n  const xp=25+(activity*10)+(likes*5)+(comments*15)+(replies*10)+(days>=7?25:0)+(['active','trialing'].includes(user.subscription_status)?100:0);\n  const level=Math.max(1,Math.floor(xp/100)+1), next=level*100;\n  const defs=[\n    ['new','🌱 Nouveau membre','Créer son compte',true],\n    ['active','🔥 Membre actif','5 actions sur le site',activity+likes+comments+replies>=5],\n    ['fan','❤️ Fan','Aimer 5 contenus',likes>=5],\n    ['commenter','💬 Bavard','Publier 3 commentaires',comments>=3],\n    ['social','🤝 Social','Répondre à 3 commentaires',replies>=3],\n    ['vip','👑 VIP','Être membre VIP actif',['active','trialing'].includes(user.subscription_status)],\n    ['top','🏆 Top membre','Atteindre le niveau 10',level>=10]\n  ];\n  for(const d of defs.filter(x=>x[3])) db.prepare("INSERT OR IGNORE INTO badges(user_id,badge_key,badge_name) VALUES(?,?,?)").run(user.id,d[0],d[1]);\n  res.json({xp,level,nextLevelXp:next,stats:{activity,likes,comments,replies},badges:defs.map(d=>({key:d[0],name:d[1],description:d[2],unlocked:d[3]}))});\n});\n\n'''
s=s[:start]+rewards+s[end:]
# make announcements route actually public regardless auth and support vip only false if unauth
# existing route currentUser works fine, open middleware means it gets user null.
p.write_text(s)
